import PropertyCard from "@/components/property/PropertyCard";
import searchIcon from "@/assets/search-icon.png";

export default function FeaturedListings() {
  const properties = [
    {
      id: 1,
      title: "Spacious 3BHK in Indiranagar",
      price: 2500000,
      address: "12 1st Main Rd, Indiranagar, Bangalore",
      beds: 3,
      baths: 2,
      image: searchIcon,
    },
    {
      id: 2,
      title: "Modern Villa in Andheri West",
      price: 4500000,
      address: "88 JP Rd, Andheri West, Mumbai",
      beds: 4,
      baths: 3,
      image: searchIcon,
    },
    {
      id: 3,
      title: "2BHK Apartment in Saket",
      price: 1800000,
      address: "B-32 Saket Block D, New Delhi",
      beds: 2,
      baths: 2,
      image: searchIcon,
    },
    {
      id: 4,
      title: "Affordable Home in Gomti Nagar",
      price: 1600000,
      address: "23 Vishal Khand, Gomti Nagar, Lucknow",
      beds: 2,
      baths: 1,
      image: searchIcon,
    },
    {
      id: 5,
      title: "Luxury Flat in Gariahat",
      price: 4200000,
      address: "9B Gariahat Rd, Ballygunge, Kolkata",
      beds: 3,
      baths: 2,
      image: searchIcon,
    },
    {
      id: 6,
      title: "Penthouse in Sector 62",
      price: 5500000,
      address: "Plot 113, Sector 62, Noida",
      beds: 4,
      baths: 4,
      image: searchIcon,
    },
    {
      id: 7,
      title: "Compact Studio in Hinjewadi",
      price: 950000,
      address: "Phase 1 Rd, Hinjewadi, Pune",
      beds: 1,
      baths: 1,
      image: searchIcon,
    },
    {
      id: 8,
      title: "Family Home in Banjara Hills",
      price: 3000000,
      address: "Road No. 10, Banjara Hills, Hyderabad",
      beds: 3,
      baths: 2,
      image: searchIcon,
    },
    {
      id: 9,
      title: "New Build in Civil Lines",
      price: 2700000,
      address: "G-12 Civil Lines, Jaipur",
      beds: 3,
      baths: 2,
      image: searchIcon,
    },
    {
      id: 10,
      title: "Classic House in Anna Nagar",
      price: 2300000,
      address: "44 V Main Rd, Anna Nagar, Chennai",
      beds: 2,
      baths: 2,
      image: searchIcon,
    },
    {
      id: 11,
      title: "Elegant Flat near Hitech City",
      price: 3200000,
      address: "Plot 21, Madhapur, Hitech City, Hyderabad",
      beds: 3,
      baths: 2,
      image: searchIcon,
    },
    {
      id: 12,
      title: "Budget 1BHK in Vasai",
      price: 800000,
      address: "Flat 304, Shanti Nagar, Vasai East, Mumbai",
      beds: 1,
      baths: 1,
      image: searchIcon,
    },
    {
      id: 13,
      title: "Cozy Home near Trivandrum Beach",
      price: 1900000,
      address: "Kovalam Rd, Vizhinjam, Trivandrum",
      beds: 2,
      baths: 1,
      image: searchIcon,
    },
    {
      id: 14,
      title: "Compact 2BHK in Sector 49",
      price: 2100000,
      address: "F-9, Sector 49, Gurgaon",
      beds: 2,
      baths: 2,
      image: searchIcon,
    },
    {
      id: 15,
      title: "Bright Villa in Jubilee Hills",
      price: 6000000,
      address: "Plot 88, Rd No. 44, Jubilee Hills, Hyderabad",
      beds: 5,
      baths: 4,
      image: searchIcon,
    },
    {
      id: 16,
      title: "Studio Apartment in MG Road",
      price: 1100000,
      address: "Tower 3, MG Road, Kochi",
      beds: 1,
      baths: 1,
      image: searchIcon,
    },
    {
      id: 17,
      title: "3BHK Flat in Chandkheda",
      price: 2000000,
      address: "Block D, Chandkheda, Ahmedabad",
      beds: 3,
      baths: 2,
      image: searchIcon,
    },
    {
      id: 18,
      title: "Luxury Condo near Marine Drive",
      price: 7500000,
      address: "9 Queens Necklace Rd, Marine Drive, Mumbai",
      beds: 4,
      baths: 4,
      image: searchIcon,
    },
    {
      id: 19,
      title: "Family Home in Whitefield",
      price: 3500000,
      address: "Plot 33, Whitefield, Bangalore",
      beds: 3,
      baths: 2,
      image: searchIcon,
    },
    {
      id: 20,
      title: "Affordable Flat in Patliputra",
      price: 1400000,
      address: "B-29, Patliputra Colony, Patna",
      beds: 2,
      baths: 1,
      image: searchIcon,
    },
    {
      id: 21,
      title: "4BHK Duplex in Aliganj",
      price: 3700000,
      address: "Plot 5, Sector C, Aliganj, Lucknow",
      beds: 4,
      baths: 3,
      image: searchIcon,
    },
    {
      id: 22,
      title: "Classic Bungalow in Vashi",
      price: 5200000,
      address: "Sector 17, Vashi, Navi Mumbai",
      beds: 4,
      baths: 3,
      image: searchIcon,
    },
    {
      id: 23,
      title: "Mid-Sized Flat in Gachibowli",
      price: 2800000,
      address: "Tower B, Gachibowli, Hyderabad",
      beds: 2,
      baths: 2,
      image: searchIcon,
    },
    {
      id: 24,
      title: "1RK in Sector 15",
      price: 700000,
      address: "RZ-18, Sector 15, Rohini, Delhi",
      beds: 1,
      baths: 1,
      image: searchIcon,
    },
    {
      id: 25,
      title: "Villa with Lawn in Porvorim",
      price: 6700000,
      address: "House 101, Porvorim, North Goa",
      beds: 4,
      baths: 3,
      image: searchIcon,
    },
    {
      id: 26,
      title: "Stylish 3BHK in Rajarhat",
      price: 2950000,
      address: "Tower 6, New Town, Rajarhat, Kolkata",
      beds: 3,
      baths: 2,
      image: searchIcon,
    },
    {
      id: 27,
      title: "Furnished 2BHK in Kharadi",
      price: 2400000,
      address: "Flat 502, Kharadi Rd, Pune",
      beds: 2,
      baths: 2,
      image: searchIcon,
    },
    {
      id: 28,
      title: "Luxury Pad near Connaught Place",
      price: 8200000,
      address: "F-21, Connaught Place, New Delhi",
      beds: 4,
      baths: 4,
      image: searchIcon,
    },
    {
      id: 29,
      title: "Spacious Flat in Sector 21",
      price: 2600000,
      address: "C-14, Sector 21, Chandigarh",
      beds: 3,
      baths: 2,
      image: searchIcon,
    },
    {
      id: 30,
      title: "2BHK in VIP Road",
      price: 1850000,
      address: "Green Tower A, VIP Road, Raipur",
      beds: 2,
      baths: 2,
      image: searchIcon,
    },
  ];

  return (
    <div className="flex flex-row flex-wrap justify-center gap-8">
      {properties.map((property) => (
        <PropertyCard key={property.id} property={property} />
      ))}
    </div>
  );
}
